spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/COMMIT_DATE
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 833793924458-io8lm1gam14qc5b0ivktu7q134u1k3sg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-name: Naver
            client-id: mbh7RztwZmet5_wxc9LC
            client-secret: rdYxmZdvxL
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
          kakao:
            client-name: Kakao
            client-id: d466dd849f1536f3a3645a839cecbf4d
            client-secret: AwYJD7wyXzd6vbO5KLj0penu4aFbpDpz
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
