spring:
  config:
    activate:
      on-profile : local

  datasource:
    url: jdbc:mysql://localhost:3306/COMMIT_CDATE
    username: myh7754
    password: DKSSUD12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create